media:
  input: exampleSite/static/images
  output: images

content:
  - name: posts
    label: Blog posts
    type: collection
    path: exampleSite/content/english/post
    filename: "{primary}.md"
    format: toml-frontmatter
    subfolders: false
    view:
      fields: [ title, date, tags ]
      primary: title
      sort: [ date, title ]
      default:
        sort: date
        order: desc
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: date, label: Date, type: date, required: true, description: "Hugo hides future dates by default." }
      - { name: author, label: Author, type: string }
      - { name: description, label: Description, type: text, options: { rows: 3 } }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: thumbnail, label: Thumbnail, type: image }
      - { name: body, label: Body, type: rich-text }
